apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: certs-volume
      mountPath: /etc/nginx/certs
      readOnly: true
  volumes:
  - name: certs-volume
    secret:
      secretName: fluentbit-certs
